Fix WIN32 compile errors due to Winsock conflicts
Fix Winsock compile errors like:

  ws2def.h(212) : error C2011: 'sockaddr' : 'struct' type redefinition

By default, windows.h includes winsock.h which is for Windows Sockets
1.1.  This will conflict with including winsock2.h which is for Windows
Sockets 2.0.  Defining WIN32_LEAN_AND_MEAN makes windows.h not include
winsock.h.  (This could also have been worked around by including
winsock2.h before windows.h.)  There are also special orderings required
for Winsock-related include files.  For more information, see:

  https://docs.microsoft.com/en-us/windows/desktop/winsock/creating-a-basic-winsock-application